"""Added 'in_practice' for theory texts and blocks

Revision ID: 6b396d6902e8
Revises: 
Create Date: 2025-06-12 15:01:36.991045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b396d6902e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_practice', sa.Boolean(), server_default='1', nullable=False))

    with op.batch_alter_table('theory_texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_practice', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theory_texts', schema=None) as batch_op:
        batch_op.drop_column('in_practice')

    with op.batch_alter_table('texts_blocks', schema=None) as batch_op:
        batch_op.drop_column('in_practice')

    # ### end Alembic commands ###
