"""init

Revision ID: aa09dfb1793c
Revises: 
Create Date: 2025-06-22 15:20:29.947561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa09dfb1793c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theory_texts', schema=None) as batch_op:
        batch_op.alter_column('block_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theory_texts', schema=None) as batch_op:
        batch_op.alter_column('block_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
