"""Add server_theory_id

Revision ID: d22ef4c822c2
Revises: 
Create Date: 2025-06-23 01:10:13.351752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22ef4c822c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theory_texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_theory_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theory_texts', schema=None) as batch_op:
        batch_op.drop_column('server_theory_id')

    # ### end Alembic commands ###
