"""add language field

Revision ID: f4577baa07f6
Revises: 6b396d6902e8
Create Date: 2025-06-21 23:21:31.751978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4577baa07f6'
down_revision = '6b396d6902e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.Enum('PYTHON', name='language_enum'), server_default='PYTHON', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
